#! /usr/bin/env sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ipt=$1
if [ -z "$ipt" ]; then
    echo -n "URL: "
    read ipt
fi
name=$(echo $ipt | awk 'BEGIN{FS="/"}{split($NF,a,/\?/); print a[1]}')
echo "Creating directory \"$name\"..."
if mkdir "$name" 2> /dev/null; then
    cd "$name"
    echo "Choose which language:"
    echo " 1. Python"
    echo " 2. C++"
    read answer
    if   [ "$answer" = "1" ]; then file="$name.py"; template="$SCRIPT_DIR/templates/empty.py"
    elif [ "$answer" = "2" ]; then file="$name.cpp"; template="$SCRIPT_DIR/templates/empty.cpp"
    else echo "No option selected, skipping this step"
    fi
    if ! [ -z "$file" ]; then
        cp "$template" "$file"
        echo "created \"$name/$file\""
        code -r "$file"
    fi
    kattis-fetchsamples "$name"
else
    echo "directory \"$name\" already exists!"
fi
